### ISSUE TITLE
Different display of the page.

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#16]
When choosing a different language, the column with subject`s names  moves out.

![Image](https://user-images.githubusercontent.com/111196939/200522277-4f3908dc-194e-4100-902c-b6dd9ef69ceb.png)

![Image](https://user-images.githubusercontent.com/111196939/200522308-e48496c0-dd6c-41aa-94ad-db441431911f.png)

![Image](https://user-images.githubusercontent.com/111196939/200522322-679fda0a-837d-4c8f-9574-8ffe224f5d06.png)

There are three different displays.

**Comment by vitalygrishin27** [comment]
It is automaticaly rendered by React
