### ISSUE TITLE
Class is not saved with access level "Teacher"

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#28]
@Associated with   https://github.com/vitalygrishin27/microfrontend-grade-book/issues/26
**ID:** 8
**Priority:** High
**Summary:** Class is not saved with access level "Teacher"

**Environment:** Google chrome (Версія
106.0.5249.119)

**Preconditions:**
1.Go to the https:
//microfrontend-grade-
book.herokuapp.com/
2. Login to the site as an admin

**Step to reproduce:**
1.  In the main menu of the page click  on the "Users" button.      
2. Click "edit" button near the user with access level "Teacher".
3.Choose class in the "class" field.
4. Click on the "save" button

![Image](https://user-images.githubusercontent.com/111196939/201891428-18bc0688-9dde-4b91-bf77-4bd41e8a9b9d.png)

5. Click tab "Teachers"

**Actual result:**
Pay attention to the list: in the column "class" there is no previously selected and saved class.

![Image](https://user-images.githubusercontent.com/111196939/201891673-f04f8c7f-9131-4baa-9e1d-3f866ca33343.png)

**Expected result:**
In the column "class" should
be the previously selected class

**Severity:** High

**Comment by vitalygrishin27** [comment]
Implemented in UI version 1.3.0 
and Service version 1.3.0

Added:
1. Deleting of Class not possible if there is at least one Pupil connected to it
2. Adding/Edditing form class for teacher not possible if another teacher already connected to this class as form master
3. Class is showed in column Class for teacher
