### ISSUE TITLE
A class can only have 1 class teacher.

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#30]
Implement the possibility that there is only 1 teacher in the class as a class teacher. When choosing a class that already has a class teacher, an error should appear:
 "A class teacher has already been assigned to this class. Please choose another one";
"Для этого класса уже назначен классный руководитель. Пожалуйста, выберите другой класс"
"За цим класом уже закріплено класного керівника. Будь ласка, оберіть інший клас"

**Comment by vitalygrishin27** [comment]
Implemented in UI 1.3.1

**Comment by iprokhorenko13** [comment]
Implemented that class can have only 1 class teacher.
When choosing a class that already has a class teacher, a notofication appear.
