### ISSUE TITLE
Too many characters in the field

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#31]
It is necessary to make a limit on the number of characters for the input field ("Classes" page - 10 characters)

![Image](https://user-images.githubusercontent.com/111196939/202158426-29df3aee-9fb0-40b8-9a5a-97f9f37a199c.png)

"Subjects" page - 30 characters
"Users" page: it`s need to discuss.

**Comment by vitalygrishin27** [comment]
For user page was set max 20 symbols for each filds

**Comment by vitalygrishin27** [comment]
Implemented in UI version 1.2.4

**Comment by iprokhorenko13** [comment]
**Tests for all pages and forms:**
1. Fill in the field with any allowed number of characters (passed)
2. Fill in the field with the maximum number of characters.+ boundary values ​​(-1; +1) - (passed)
3.  Click create an entry without filling in anything (passed)
4. Press the spacebar several times while in the field, and then press save entry
 (failed).

**Comment by iprokhorenko13** [comment]
The problem is solved in the task
https://github.com/vitalygrishin27/microfrontend-grade-book/issues/38
