### ISSUE TITLE
The words "filter" and "sorting" are not displayed in the selected language

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#32]
**ID:** 9
**Priority:** Medium

**Summary:** The words "filter" and "sorting" are not displayed in the selected language

**Environment:** Google chrome (version 107.0.5304.107)

**Preconditions:**
1.Go to the https:
//microfrontend-grade-
book.herokuapp.com/
2. Login to the site as an admin

**Step to reproduce:**
1.  In the main menu of the page click on the "Users" button.

**Actual result:**
Pay attention to the chosen language and to the  words "Filters", "Sorting"

![Image](https://user-images.githubusercontent.com/111196939/202439545-c47b615c-6e05-4c53-84bc-4f3f064c5179.png)

**Expected result:**
The words "filter" and "sorting" should be displayed on the same language as the selected one

**Severity:** Low

**Comments:** At the "RU" lokalization
 the same situation (pages "Classes", "Users", "Subjects").

**Comment by vitalygrishin27** [comment]
Fixed in Version UI version 1.3.1

**Comment by iprokhorenko13** [comment]
It fixed only on the page "Users".
Pages "Classes" and "Subjects" have a bug with RU and UA lokalozation.


![Image](https://user-images.githubusercontent.com/111196939/202459229-8d5f664a-0dfd-4d14-b349-2951edd4f47f.png)



![Image](https://user-images.githubusercontent.com/111196939/202459387-93e9c18b-704e-4d39-b062-4f9c276f9292.png)

**Comment by vitalygrishin27** [comment]
Fixed in UI version 1.3.3

**Comment by iprokhorenko13** [comment]
The words "filter" and "sorting"  displays on the same language as the selected one
