### ISSUE TITLE
Notification when trying to delete a record about a class

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#33]
Need to change the notification when trying to delete an entity about a class.

**If it possible to write big message (it is more understandable) it will be the next:**
"Ви не можете видалити клас, оскільки в ньому є учні"
"Вы не можете удалить класс, поскольку в нем есть ученики"
"You cannot delete a class because it has pupils"

**If it unposiible it will be the next variant:**
"У вибраному класі є учні"
"В выбранном классе есть ученики"
"There are students in the class"

**Comment by iprokhorenko13** [comment]
In "RU" localiation displays the old notification.


![Image](https://user-images.githubusercontent.com/111196939/202687584-a26e5f00-9895-4dcf-ba15-90e49f581e32.png)

**Comment by vitalygrishin27** [comment]
Fixed in Ui version 1.4.4

**Comment by iprokhorenko13** [comment]
Checked. It works correctly.
