### ISSUE TITLE
Notification when search results are null

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#35]
When nothing is found by the filter, a notification may be needed to make it clear that the server checked everything, but did not find such information.
**It can be such like this:**

За Вашим запитом нічого не знайдено
По этому запросу ничего не найдено
Nothing found for this search

**Comment by vitalygrishin27** [comment]
Done in UI version 1.4.2

**Comment by iprokhorenko13** [comment]
It works correct
