### ISSUE TITLE
Search function. Take a step back.

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#37]
Is there a solution so that after displaying the search results, you can return to the page displaying all the records on the page?
Because right now it works like this:
1. Entered a query in the search field
2. Result shown
When you click on the tab in which the search was made, nothing happens, only the result that was found by the search is displayed. It turns out that you can return to the full list only after you remove the request from the "search" field.

**Comment by vitalygrishin27** [comment]
Yes. Only like this now. Because there is no history

**Comment by vitalygrishin27** [comment]
Maybe later somewhen we will return to this question
