### ISSUE TITLE
Ability to save an empty entry  by entering spaces

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#38]
**ID:** 10
**Priority:** High

**Summary:** Ability to save an empty entry by entering spaces

**Environment:** Google chrome (version 107.0.5304.107)

**Preconditions:**
1.Go to the https:
//microfrontend-grade-
book.herokuapp.com/
2. Login to the site as an admin

**Step to reproduce:**

1.  In the right corner of the page, click on the "Class" button. 
2.  Click on the "+" button
3.In an empty field, press the spacebar several times.
4. Click on the "create" button.

**Actual result:**

Pay attention to the list: empty entry saved.

![Image](https://user-images.githubusercontent.com/111196939/202847376-e89480c6-4a5e-4a07-b989-82e564e15e13.png)

**Expected result:** 
A notification appears with 
the text "Поле не может быть пустым"
Field cannot be empty
"Поле не може бути пустим" 

and the entity should not be stored in the database

**Severity:** High

**Comments:**
Page “Users” and 
Page “Subjects” have the same problem.

![Image](https://user-images.githubusercontent.com/111196939/202847381-0e1671a1-2d9e-4d62-b710-bc75da38b8d0.png)

![Image](https://user-images.githubusercontent.com/111196939/202847383-1a358545-d4df-46ac-9585-f000d9a086e1.png)

**Comment by vitalygrishin27** [comment]
Fixed in service version 1.3.4

**Comment by iprokhorenko13** [comment]
Checked. We cannot save an entity with an empty entry by entering spaces
