### ISSUE TITLE
Unable to login to account

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#4]
![Image](https://user-images.githubusercontent.com/111196939/199052911-5a43cc76-0572-45fc-9f2a-f6eb3bd5bd6d.png)

**Comment by vitalygrishin27** [comment]
Root cause of the issue is that several requests are processing in microservice and create few tokens in DB
But DB has restrictions for only 1 token per user.
Solution: Need to block the submit button until a response is received from the server.

**Comment by iprokhorenko13** [comment]
The error is not reproduced. Button locked
