### ISSUE TITLE
Wrong notification with adding the class

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#40]
**ID:** 11

**Priority:** Low

**Summary:** Wrong notification with adding the class
**Environment:** Google chrome (Версія 107.0.5304.107)

**Preconditions:**
1.Go to the https:
//microfrontend-grade-
book.herokuapp.com/
2. Login to the site as an admin

**Step to reproduce:**
1.  On the main menu click on the "Users" button. 
2.  Click on the "Teachers" tab
3. Click "edit" button near the teacher`s name, who don`t have a class.
4. In open form choose the class, that have already chosen earlier to another teacher.
5. Click on the "Save" button.  

**Actual result:**
Pay attention to the notification: it is wrong notification. We do not delete the entity.

![Image](https://user-images.githubusercontent.com/111196939/203011932-b924f89f-5fff-44b6-bb9b-af36d115797c.png)

**Expected result:**
A notification will appear with the following
text:
"A class teacher has already been assigned to this class. Please choose another one";
"Для этого класса уже назначен классный руководитель. Пожалуйста, выберите другой класс"
"За цим класом уже закріплено класного керівника. Будь ласка, оберіть інший клас"

**Severity:** Medium

**Comment by vitalygrishin27** [comment]
Fixed in Ui version 1.4.4

**Comment by iprokhorenko13** [comment]
Checked. It works correctly.
