### ISSUE TITLE
Another name for the button

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#45]
I have a suggestion: change the name of the button "Show students" to 
"List of students"
"Список учеников"
"Список учнів"

![Image](https://user-images.githubusercontent.com/111196939/205339056-741d6831-2201-41c6-a1ad-1751c5d4af2f.png)

**Comment by vitalygrishin27** [comment]
Availbale in UI version 2.1.0
I leave pupils instead students because pupils are everywhere on our pages

**Comment by iprokhorenko13** [comment]
Sorry. It was about list. 
List of pupils

**Comment by iprokhorenko13** [comment]
This feature tested. 
Test passed.
