### ISSUE TITLE
Uncorrect notification

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#46]
**Summary:** Uncorrect notification
**Priority:** Low
**Preconditions:**
Go to the https://microfrontend-grade-book.herokuapp.com/
Login to the site as an admin

**Steps:**
1.	In the right corner of the page, click on the "Subjects" button.
2.	Enter some word in the "search" field
3.	Click on the "search" button or “enter” button.

**Actual result:**
The notification appears with text " No results were found for this search”

![Image](https://user-images.githubusercontent.com/111196939/205343118-34e27e0c-c866-4e0e-9d91-9b14eaee23f8.png)

**Expected result:**
The notification appears with text 
" Search field cannot be empty”
Поле поиска не может быть пустым
Поле пошуку не може бути порожнім

**Comments:** 
Change the word "пустим" to "порожнім" in other notifications in the UA localization

**Comment by vitalygrishin27** [comment]
if we search for empty query - error message can be the same as it is
