### ISSUE TITLE
Storing the same values ​​in the database

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#54]
**ID:** 14
**Priority:** High
**Summary:** The ability to add the name of the same subject

**Environment:** Google chrome (Версія 108.0.5359.125)

**Preconditions:**
1.Go to the https:
//microfrontend-grade-
book.herokuapp.com/
2. Login to the site as an admin

**Step to reproduce:**
1.	Added subjects using UI
2.	Ran scripts in the database, where were the names of the items that was added using UI

**Actual result:**
Pay attention to the general list: There are the same subjects names in the list
 

![Image](https://user-images.githubusercontent.com/111196939/208687334-f22727b6-f6c1-44db-aee1-57665a83a6ef.png)

**Expected result:**
There should have been a notification about already existing subjects.
**Severity:** High

**Comment by vitalygrishin27** [comment]
It is possible to do via script but not via UI.
Task can be closed
