### ISSUE TITLE
Uncorrect notification

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#55]
On the "Scheduler" page, when dragging an subject to the day column, the word "subject" must be added to the notification:
«Невозможно добавить предмет, за которым не закреплен учитель»
«Неможливо додати предмет, за яким не закріплено вчителя»
"Impossible to add a subject that isn't assigned to a teacher"

![Image](https://user-images.githubusercontent.com/111196939/208692688-254cb6e1-f201-4c7e-9e88-bc155c92b043.png)

Comments: need to change in all lokalizations.

**Comment by vitalygrishin27** [comment]
Fixed in UI version 3.0.7

**Comment by iprokhorenko13** [comment]
On the Planner page, when dragging a subject without a selected teacher into the day column, the correct notification appears (passed).
