### ISSUE TITLE
One teacher can only teach 1 lesson at a time.

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#56]
As a rule, it is not possible for the same teacher to teach 2 classes in parallel at the same time. This is like an exceptional case, which is not included in the general schedule.

![Image](https://user-images.githubusercontent.com/111196939/208877562-f10ec0ce-52f7-45cf-805d-75efcaff3d48.png)

![Image](https://user-images.githubusercontent.com/111196939/208877582-acfcf066-a180-4577-a273-935da52bf4af.png)

**Comment by vitalygrishin27** [comment]
Subject box will be with red border if some conflicts appears. Additional info shows by clicking on box.
After saving - scheduler will update information about conflicts
Implemented in UI version 3.0.8 Service version 3.1.0

**Comment by iprokhorenko13** [comment]
Checked. When one of the subjects is added to the schedule, and at this time the teacher is teaching a lesson in another class (that is, a conflict occurs), the subject field becomes red.
