### ISSUE TITLE
Reduction of space with objects

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#57]
Make the space with objects smaller so that most of the objects can be seen at once, since the number of objects is large, and it is inconvenient to scroll down for a long time in order to find the necessary object.

![Image](https://user-images.githubusercontent.com/111196939/208877950-81b4fdf1-ea55-425f-b5a7-a3251a6315b3.png)

**Comment by vitalygrishin27** [comment]
After disscussion - task was closed
