### ISSUE TITLE
Incorrect inscription

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#60]
It needs to decide:

![Image](https://user-images.githubusercontent.com/111196939/209107170-92938bc5-a6d5-470d-92c0-8d30a071f827.png)

This means that the teacher does not have a lesson, that is, he does not have free time as we mean as usual, but a free hour of the lesson. I think "free hour" sounds more formal.

**Comment by vitalygrishin27** [comment]
Corrected in UI version 3.0.7

**Comment by iprokhorenko13** [comment]
Checked. It is changed.
