### ISSUE TITLE
Removing a subject from a user

### ISSUE THREAD

**Issue by iprokhorenko13** [vitalygrishin27/microfrontend-grade-book#61]
When a subject with the selected teacher has already been added to the schedule, and then this subject is removed from the user card, but this subject remains in the schedule on the selected day and the teacher too.

![Image](https://user-images.githubusercontent.com/111196939/209107592-be27435a-cc6c-4057-887f-fc88c735cfe5.png)

Perhaps you need to automatically remove it from the "Schedule" page, that is, the name of the teacher, and this it will be in the general list of subjects.

**Comment by vitalygrishin27** [comment]
Implemented in version 3.0.7

**Comment by iprokhorenko13** [comment]
Checked. This function works correctly.
